/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Layout: typeof import('./src/components/layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TCheckBox: typeof import('./src/components/tCheckBox.vue')['default']
    TIcon: typeof import('./src/components/tIcon.vue')['default']
    TSelect: typeof import('./src/components/tSelect.vue')['default']
    TTheme: typeof import('./src/components/tTheme.vue')['default']
    VPdf: typeof import('@whykhamist/vpdf')['VPdf']
  }
}
